apiVersion: apps/v1
kind: Deployment
metadata:
  name: mountprotocol-xyz-deployment
  labels:
    apptype: mountprotocol-xyz
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: mountprotocol-xyz
  template:
    metadata:
      labels:
        app: mountprotocol-xyz
        apptype: mountprotocol-xyz
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: mountprotocol-xyz
          image: gitdatateam/mountprotocol-xyz:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
