apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  mountprotocol-xyz
  annotations:
    meta.helm.sh/release-name: mountprotocol-xyz
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    apptype: mountprotocol-xyz
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release:  mountprotocol-xyz
spec:
  ingressClassName: {{.Values.ingress_name}}
  rules:
    - host: mountprotocol.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mountprotocol-xyz-service
                port:
                  number: 80
